name: app

type: php:7.0
build:
  flavor: composer

runtime:
    extensions:
        - redis
        - mcrypt
        - imap
        - xdebug

relationships:
    database: 'mysqldb:mysql'
    redis: 'rediscache:redis'

web:
    locations:
      '/':
        root: 'mautic'
        passthru: '/index.php'
        index:
          - 'index.php'
        allow: true
        scripts: true

disk: 2048

mounts:
  "persistent/": "shared:files/persistent"
  "mautic/app/cache": "shared:files/cache"
  "mautic/app/logs": "shared:files/logs"
  "mautic/translations": "shared:files/translations"
  "mautic/media": "shared:files/medi"

hooks:
  build: |
    set -e
    cd mautic
    composer install
    npm install
    npm install grunt-cli
    ./node_modules/.bin/grunt less
    cd /app/mautic/app/config
    ln -fs ../../../persistent/local.php local.php
    cd /app/mautic
    mv media _media
    mkdir media

  deploy: |
    set -e
    if [ ! -f /app/persistent/local.php ]; then
      cp /app/config.php /app/persistent/local.php
    fi;
    if [ ! -f /app/persistent/installed ]; then
      cd /app/mautic
      cp -R _media/* media/
      # php app/console mautic:install:data
      touch /app/persistent/installed
    fi;
    cd /app/mautic
    php app/console doctrine:migrations:migrate

crons:
  segments:
    spec: "0,15,30,45 * * * *"
    cmd: "php /app/mautic/app/console  mautic:segments:update"
  campaignsupdate:
    spec: "5,20,35,50 * * * *"
    cmd: "php /app/mautic/app/console  mautic:campaigns:update"
  campaignstrigger:
    spec: "10,25,40,55 * * * *"
    cmd: "php /app/mautic/app/console  mautic:campaigns:trigger"
